### ISSUE TITLE
It should be possible to only generate a specific API

### ISSUE THREAD

**Issue by mxsc** [lunarway/SwaggerSwift#24]
Now when we run swaggerswift it regenerates all our APIs, but sometimes it would make sense to only generate the desired service(s). We could easily ending up adding breaking changes by regenerating the service.

**Comment by MadsBogeskov** [comment]
So what you want is something like `swaggerswift --api lunarway/my_api` or more specific like `swaggerswift --api lunarway/my_api --endpoint /get` ?

**Comment by mxsc** [comment]
precisely more the first part, not as granular as per endpoint. More based on the swagger input file, then you can do most of it locally.

**Comment by MadsBogeskov** [comment]
Is this to support using a custom branch? Because what do you want to do about the already existing api defined in the SwaggerFile?

e.g. SwaggerFile:
```
services:
  - lunarway/my_service
```

and then
`swaggerswift --api lunarway/my_service@featureBranch`

**Comment by mxsc** [comment]
but on second thought I think the branch as part of this does not make sense, since you cannot get the same code by running the same command.

**Comment by mxsc** [comment]
Closing added in #25
